# Dados Numéricos

In [5]:
# Variável inteira
a = 1
print('Valor de a = '+str(a))
type(a)

Valor de a = 1


int

In [6]:
# Variável dupla precisão
b = 1.0
print(b)
type(b)

1.0


float

In [7]:
# Converter float para int
c = int(b)
print(c)
type(c)

1


int

In [8]:
# Delacrando nan
import numpy as np
d = np.nan
print(d)
type(d)

nan


float

In [9]:
# Operação com NaN
e = d*1
print(e)
e = d+1
print(e)
e = np.nansum([d,1])
print(e)

nan
nan
1.0


# Dados de Texto

In [11]:
# Declaração de variável texto
f = 'Fábio'
g = "Gabriel"
print(f)
print(g)
print(f+g)
print(f+' '+g)

Fábio
Gabriel
FábioGabriel
Fábio Gabriel


# Dados tipo bool - lógica

In [12]:
a == 1

True

In [13]:
h = (a==1)
print(h)
type(h)

True


bool

In [14]:
h = (a==2)
print(h)
type(h)

False


bool

In [15]:
i = True
type(i)

bool

In [16]:
ii = 'True'
type(ii)

str

# Operação de comparação

In [17]:
# Operação ==
a==b

True

In [18]:
# Operação ><
a>b

False

In [19]:
# Operação !=
a!=b

False

In [20]:
# Operação >= ou <=
a>=b

True

# Operações matemáticas

In [21]:
# Soma 
a+b

2.0

In [22]:
# Soma e atribui valor
ab = a+b
print(ab)

2.0


In [23]:
# Multiplicação
l = a*b # Não use l como variável
print("Não use l como nome de variável")
j = a*b
print(j)

Não use l como nome de variável
1.0


In [24]:
# Divisão
a/b

1.0

In [25]:
# Potencia
5**2

25

In [26]:
# Operações matemáticas com a bibliotéca math
import math

math.exp(10)

22026.465794806718

In [27]:
math.exp(0)

1.0

In [28]:
math.exp(a)

2.718281828459045

In [29]:
math.exp(-10)

4.5399929762484854e-05

In [30]:
import math as mt
mt.log(c)

0.0

In [31]:
mt.log10(100)

2.0

# Listas

In [32]:
myFirstList = [1,2,3]
print(myFirstList)

[1, 2, 3]


In [33]:
# Acessando valores da lista pelo index
print(myFirstList[0])
print(myFirstList[2])

1
3


In [34]:
myFirstList==a

False

In [35]:
myFirstList[0]==a

True

In [36]:
mySecList = [1,a,'c']
print(mySecList)

[1, 1, 'c']


In [37]:
type(mySecList)

list

In [38]:
type(mySecList[2])

str

In [39]:
type(mySecList[1])

int

# Caminhos = path

In [40]:
path = r"C:\Users\dodo_\Documents\GitHub\ENS5173_202401"
print(path)

C:\Users\dodo_\Documents\GitHub\ENS5173_202401


In [41]:
path = "C:/Users/dodo_/Documents/GitHub/ENS5173_202401"
print(path)

C:/Users/dodo_/Documents/GitHub/ENS5173_202401


In [42]:
import os
# Listar arquivos na pasta
os.listdir(path)

['.git',
 '.gitignore',
 '.ipynb_checkpoints',
 'Aula01.ipynb',
 'inputs',
 'pyEnv',
 'README.md',
 'scripts',
 'venv']

In [43]:
# Selecionar primeiro arquivo listado
os.listdir(path)[0]

'.git'

In [44]:
# Concatenando caminhos
path+"/"+os.listdir(path)[0]

'C:/Users/dodo_/Documents/GitHub/ENS5173_202401/.git'

In [45]:
# Listando caminho concatenado
os.listdir(path+"/"+os.listdir(path)[0])

['COMMIT_EDITMSG',
 'config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'packed-refs',
 'refs']

In [46]:
# Diretório que estou trababalhando
os.getcwd()

'C:\\Users\\dodo_\\Documents\\GitHub\\ENS5173_202401\\pyEnv\\Scripts'

In [ ]:
# Mudo de diretório para o caminho 
os.chdir('C:\\Users\\dodo_\\Documents\\GitHub\\')

In [47]:
os.getcwd()

'C:\\Users\\dodo_\\Documents\\GitHub\\ENS5173_202401\\pyEnv\\Scripts'

In [48]:
# Criando diretório
new_path = os.getcwd()+'/test'

if os.path.isdir(new_path):
    print('diretório já existe')
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)

Criando diretório C:\Users\dodo_\Documents\GitHub\ENS5173_202401\pyEnv\Scripts/test


In [49]:
# Criando diretório
new_path = os.getcwd()+'/test2'

if os.path.isdir(new_path):
    print('diretório já existe')
    # Criando um arquivo de texto
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")

Criando diretório C:\Users\dodo_\Documents\GitHub\ENS5173_202401\pyEnv\Scripts/test2


# Numpy arrays e Pandas DataFrames

In [50]:
import numpy as np
# Criando uma variável numpy
n = np.array(0)
type(n)

numpy.ndarray

In [51]:
# Criando uma variável numpy a partir de uma lista
myThirdList=[1,2,3,10,20,55]
n = np.array(myThirdList)
print(n)

[ 1  2  3 10 20 55]


In [52]:
# Criando uma matriz de 10x10 de números aleatórios entre 0 e 1
n = np.random.rand(10,10)
print(n)
# Dimensões da matrix
print(n.shape)

[[0.62943858 0.0828187  0.71557774 0.03611695 0.76341502 0.10334714
  0.86967139 0.45284454 0.71602396 0.48212474]
 [0.08349735 0.40097086 0.93616656 0.29032046 0.69814945 0.81658357
  0.33865303 0.67728755 0.69493404 0.09370856]
 [0.36063969 0.43089948 0.01025486 0.9339408  0.60357667 0.21157943
  0.11151918 0.48473061 0.25829768 0.52394137]
 [0.03678322 0.0251025  0.55583248 0.36643152 0.13741143 0.60281331
  0.13822654 0.82959914 0.85331232 0.71284758]
 [0.07685369 0.26493742 0.77060299 0.43938838 0.15773131 0.30229702
  0.76641245 0.13493703 0.98878971 0.22805357]
 [0.8481391  0.56716833 0.09430862 0.43847543 0.74866808 0.98617958
  0.48578408 0.11663384 0.31108853 0.94460343]
 [0.64994027 0.57908686 0.97800025 0.14911254 0.19027074 0.90867621
  0.41068296 0.89299382 0.35881791 0.11793802]
 [0.64686241 0.07592003 0.8358625  0.07689015 0.67200759 0.62867208
  0.16627362 0.21144685 0.57077499 0.00608132]
 [0.35605621 0.48337445 0.5565816  0.17081462 0.94192453 0.03322656
  0.73235142

In [53]:
# Acessando valores da matriz
n[0,:]

array([0.62943858, 0.0828187 , 0.71557774, 0.03611695, 0.76341502,
       0.10334714, 0.86967139, 0.45284454, 0.71602396, 0.48212474])

In [54]:
n[:,0]

array([0.62943858, 0.08349735, 0.36063969, 0.03678322, 0.07685369,
       0.8481391 , 0.64994027, 0.64686241, 0.35605621, 0.24049306])

In [55]:
n[:,1:5]

array([[0.0828187 , 0.71557774, 0.03611695, 0.76341502],
       [0.40097086, 0.93616656, 0.29032046, 0.69814945],
       [0.43089948, 0.01025486, 0.9339408 , 0.60357667],
       [0.0251025 , 0.55583248, 0.36643152, 0.13741143],
       [0.26493742, 0.77060299, 0.43938838, 0.15773131],
       [0.56716833, 0.09430862, 0.43847543, 0.74866808],
       [0.57908686, 0.97800025, 0.14911254, 0.19027074],
       [0.07592003, 0.8358625 , 0.07689015, 0.67200759],
       [0.48337445, 0.5565816 , 0.17081462, 0.94192453],
       [0.314584  , 0.32149109, 0.51111633, 0.98121199]])

In [56]:
n[0,1:5]

array([0.0828187 , 0.71557774, 0.03611695, 0.76341502])

In [57]:
n[0,-1]

0.4821247433947349

In [58]:
n[0,4:-1]

array([0.76341502, 0.10334714, 0.86967139, 0.45284454, 0.71602396])

In [59]:
n[0,4:]

array([0.76341502, 0.10334714, 0.86967139, 0.45284454, 0.71602396,
       0.48212474])

In [60]:
an = np.log(n*5)
print(an)

[[ 1.14651092 -0.88166349  1.27477288 -1.71155499  1.33948445 -0.66022374
   1.46979806  0.81723151  1.27539627  0.87988552]
 [-0.87350244  0.69557139  1.54347605  0.37266798  1.25011583  1.40681189
   0.52665871  1.21977855  1.24549956 -0.75812778]
 [ 0.589562    0.76755746 -2.97056558  1.54109568  1.10455572  0.0562831
  -0.58412082  0.88527592  0.25579535  0.96306243]
 [-1.69327548 -2.07534988  1.02214959  0.6054943  -0.37533779  1.10329018
  -0.36942341  1.42262526  1.45080826  1.27095026]
 [-0.95641382  0.28117629  1.34885595  0.78706635 -0.23742434  0.41309268
   1.34340311 -0.39350912  1.59816431  0.13126318]
 [ 1.44472729  1.04233877 -0.75174479  0.78498641  1.31997837  1.5955211
   0.88744688 -0.53927792  0.44176015  1.55244782]
 [ 1.1785631   1.06313512  1.58719256 -0.29361606 -0.04986936  1.51367145
   0.71950417  1.4962623   0.58449767 -0.52815814]
 [ 1.17381625 -0.96863679  1.43014675 -0.9559396   1.21195227  1.14529242
  -0.18468265  0.05565628  1.04867769 -3.49309578]
 [